FROM node:24.14-slim

ENV NODE_ENV=production

WORKDIR /src

RUN apt-get update && apt-get install -y \
    make \
    libtool \
    libsodium-dev \
    autoconf \
    automake \
    g++ \
    python3 \
    ffmpeg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ["package.json", "package-lock.json*", "./"]

RUN npm ci --omit=dev && npm cache clean --force

COPY . .

CMD ["npm", "start"]